name: fancy_intro_carousel_slider
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/iamnijat/fancy-intro-carousel-slider.git

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
